"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.deleteLayer = exports.updateLayer = exports.createLayer = exports.deleteAIModel = exports.updateAIModel = exports.createAIModel = exports.deleteUser = exports.updateUser = exports.createUser = void 0;
exports.createUser = "\n  mutation CreateUser(\n    $input: CreateUserInput!\n    $condition: ModelUserConditionInput\n  ) {\n    createUser(input: $input, condition: $condition) {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.updateUser = "\n  mutation UpdateUser(\n    $input: UpdateUserInput!\n    $condition: ModelUserConditionInput\n  ) {\n    updateUser(input: $input, condition: $condition) {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.deleteUser = "\n  mutation DeleteUser(\n    $input: DeleteUserInput!\n    $condition: ModelUserConditionInput\n  ) {\n    deleteUser(input: $input, condition: $condition) {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.createAIModel = "\n  mutation CreateAIModel(\n    $input: CreateAIModelInput!\n    $condition: ModelAIModelConditionInput\n  ) {\n    createAIModel(input: $input, condition: $condition) {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.updateAIModel = "\n  mutation UpdateAIModel(\n    $input: UpdateAIModelInput!\n    $condition: ModelAIModelConditionInput\n  ) {\n    updateAIModel(input: $input, condition: $condition) {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.deleteAIModel = "\n  mutation DeleteAIModel(\n    $input: DeleteAIModelInput!\n    $condition: ModelAIModelConditionInput\n  ) {\n    deleteAIModel(input: $input, condition: $condition) {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.createLayer = "\n  mutation CreateLayer(\n    $input: CreateLayerInput!\n    $condition: ModelLayerConditionInput\n  ) {\n    createLayer(input: $input, condition: $condition) {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
exports.updateLayer = "\n  mutation UpdateLayer(\n    $input: UpdateLayerInput!\n    $condition: ModelLayerConditionInput\n  ) {\n    updateLayer(input: $input, condition: $condition) {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
exports.deleteLayer = "\n  mutation DeleteLayer(\n    $input: DeleteLayerInput!\n    $condition: ModelLayerConditionInput\n  ) {\n    deleteLayer(input: $input, condition: $condition) {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
