"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.onDeleteLayer = exports.onUpdateLayer = exports.onCreateLayer = exports.onDeleteAIModel = exports.onUpdateAIModel = exports.onCreateAIModel = exports.onDeleteUser = exports.onUpdateUser = exports.onCreateUser = void 0;
exports.onCreateUser = "\n  subscription OnCreateUser {\n    onCreateUser {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onUpdateUser = "\n  subscription OnUpdateUser {\n    onUpdateUser {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onDeleteUser = "\n  subscription OnDeleteUser {\n    onDeleteUser {\n      id\n      name\n      models {\n        items {\n          id\n          name\n          source\n          data\n          createdAt\n          updatedAt\n          userModelsId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onCreateAIModel = "\n  subscription OnCreateAIModel {\n    onCreateAIModel {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.onUpdateAIModel = "\n  subscription OnUpdateAIModel {\n    onUpdateAIModel {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.onDeleteAIModel = "\n  subscription OnDeleteAIModel {\n    onDeleteAIModel {\n      id\n      name\n      source\n      data\n      layers {\n        items {\n          id\n          name\n          type\n          defaultParams\n          createdAt\n          updatedAt\n          aIModelLayersId\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n      userModelsId\n    }\n  }\n";
exports.onCreateLayer = "\n  subscription OnCreateLayer {\n    onCreateLayer {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
exports.onUpdateLayer = "\n  subscription OnUpdateLayer {\n    onUpdateLayer {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
exports.onDeleteLayer = "\n  subscription OnDeleteLayer {\n    onDeleteLayer {\n      id\n      name\n      type\n      defaultParams\n      createdAt\n      updatedAt\n      aIModelLayersId\n    }\n  }\n";
